name: healthcare-translation-backend
region: nyc
services:
- name: backend
  github:
    repo: charliepaks/healthcare-translation-app
    branch: main
    deploy_on_push: true
  source_dir: /backend  # Critical - points to your backend directory
  http_port: 8000
  instance_size: basic-xxs
  instance_count: 1
  
  # System-wide dependencies (including FFmpeg)
  system_packages:
    - ffmpeg
    - python3-dev
    - build-essential  # Required for some Python packages
  
  # Python-specific configuration
  environment_slug: python-3.11
  run_command: |
    gunicorn app.main:app \
    --workers 2 \
    --worker-class uvicorn.workers.UvicornWorker \
    --timeout 60 \
    --bind :8000 \
    --access-logfile -
    
  build_command: |
    pip install --no-cache-dir -r requirements.txt
  
  # Environment variables (add others from .env.example here)
  envs:
    - key: PORT
      value: "8000"
    - key: PYTHONUNBUFFERED
      value: "1"
    # Add other required variables like:
    # - key: OPENAI_API_KEY
    #   value: your-key-here
    # - key: SECRET_KEY
    #   value: your-secret-here